# Generated by Django 6.0.1 on 2026-01-27 18:14

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.max_size_kb]),
        ),
    ]
